version: "3"
services:
  app:
    build:
      context: .
      args:
        NPM_TOKEN: ${NPM_TOKEN}
    image: 163482350712.dkr.ecr.eu-west-1.amazonaws.com/appquality-pagebuilder-poc
    ports:
      - "3000:80"
